force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Unit__c/Contract_Unit__c.object-meta.xml
<CustomObject>
    <description>To register Contract Units</description>
    <label>Contract Eenheid</label>
    <nameField>
        <label>Contract Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Eenheden</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Unit__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>To register the address</description>
    <inlineHelpText>To register the address</inlineHelpText>
    <label>Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Contract_Unit__c/fields/Correction__c.field-meta.xml
<CustomField>
    <fullName>Correction__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field for updating using a batch</description>
    <inlineHelpText>Temporary field for updating using a batch</inlineHelpText>
    <label>Correction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateAddressBatchTest 2.cls
/**
 * Created by harm on 23/06/2025.
 */

@IsTest
private class UpdateAddressBatchTest {
    @IsTest
    static void testAddress() {
        List<Address__c> testAddresses = TestDataFactory.getAddresses(300);
        insert testAddresses;
        Test.startTest();
        System.assertEquals(300, [SELECT count() FROM Address__c WHERE Correction__c = false],'Expected 300 addresses untouched');
        UpdateAddressesBatch.startBatch('SELECT Id FROM Address__c WHERE Correction__c=false LIMIT 200');
        Test.stopTest();
        System.assertEquals(100, [SELECT count() FROM Address__c WHERE Correction__c = false],'Expected 100 addresses untouched');
        System.assertEquals(200, [SELECT count() FROM Address__c WHERE Correction__c = true],'Expected 200 addresses updated');
    }
    @IsTest
    static void testContractUnit() {
        List<Contract_Unit__c> testUnits = new List<Contract_Unit__c>();
        testUnits.add(TestDataFactory.getContractUnit('apex1'));
        testUnits.add(TestDataFactory.getContractUnit('apex2'));
        insert testUnits;
        Test.startTest();
        System.assertEquals(2, [SELECT count() FROM Contract_Unit__c WHERE Correction__c = false],'Expected 2 contract units untouched');
        UpdateAddressesBatch.startBatch('SELECT Id FROM Contract_Unit__c WHERE Correction__c=false LIMIT 1');
        Test.stopTest();
        System.assertEquals(1, [SELECT count() FROM Contract_Unit__c WHERE Correction__c = false],'Expected 1 contract unit untouched');
        System.assertEquals(1, [SELECT count() FROM Contract_Unit__c WHERE Correction__c = true],'Expected 1 contract unit updated');
    }
}